### Assigning Subsequent Rows to Matrix first row elements
Input : test_list = [[5, 8, 10], [2, 0, 9], [5, 4, 2], [2, 3, 9]]<br>Output : {5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]} <br>
Explanation : 5 paired with 2nd row, 8 with 3rd and 10 with 4th 

In [1]:
import numpy as np

In [8]:
list = np.array([[5, 8, 10], [2, 0, 9], [5, 4, 2], [2, 3, 9]])
print(list)

[[ 5  8 10]
 [ 2  0  9]
 [ 5  4  2]
 [ 2  3  9]]


In [10]:
a = list[0]
b = list[1:len(list)]
d = dict()
for i in range(0,len(a)):
    d[a[i]] = b[i]
    
str(d)

'{np.int64(5): array([2, 0, 9]), np.int64(8): array([5, 4, 2]), np.int64(10): array([2, 3, 9])}'

### Adding and Subtracting Matrices in Python
Suppose we have two matrices A and B.<br>
A = [[1,2],[3,4]]<br>
B = [[4,5],[6,7]]<br>

then we get<br>
A+B = [[5,7],[9,11]]<br>
A-B = [[-3,-3],[-3,-3]]<br>

In [15]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

print(a)

[[1 2]
 [3 4]]


In [17]:
print(b)

[[4 5]
 [6 7]]


In [20]:
print(np.add(a,b))

[[ 5  7]
 [ 9 11]]


### Group similar elements into Matrix
Input : test_list = [1, 3, 4, 4, 2, 3] <br>
Output : [[1], [2], [3, 3], [4, 4]] 

In [24]:
a = np.array([1, 3, 4, 4, 2, 3])
print(a)

[1 3 4 4 2 3]


In [28]:
res = []

for i in a:
    found = False
    for j in range(len(res)):
        if i in res[j]:
            res[j].append(i)
            found = True
            break
    if not found:
        res.append([i])

print(str(res))

[[np.int64(1)], [np.int64(3), np.int64(3)], [np.int64(4), np.int64(4)], [np.int64(2)]]


###  Row-wise element Addition in Tuple Matrix
input : test_list = [[('Gfg', 3)], [('best', 1)]] cus_eles = [1, 2] <br>
Output : [[('Gfg', 3, 1)], [('best', 1, 2)]] 

In [33]:
test_list = [[('Gfg', 3)], [('best', 1)]]
cus_eles = [1, 2]

result_list = []
for i, row in enumerate(test_list):
    new_row = [(tup + (cus_eles[i],)) for tup in row]
    result_list.append(new_row)

print(result_list)

[[('Gfg', 3, 1)], [('best', 1, 2)]]


### Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even
input: 2 <br>
Output: 1 2 <br>
4 3 <br>
Explanation: Here sum of 1+3=4 is even and 2+4=6 is even<br>

In [34]:
def generate_matrix(n):
    matrix = [[0]*n for _ in range(n)]
    low = 1
    high = n * n
    
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                matrix[i][j] = low
                low += 1
            else:
                matrix[i][j] = high
                high -= 1
    
    for row in matrix:
        print(*row)

generate_matrix(2)

1 4
3 2
